import Vue from 'vue';
import { library } from "@fortawesome/fontawesome-svg-core";
import { faJs, faVuejs } from "@fortawesome/free-brands-svg-icons";
import { faCoffee } from "@fortawesome/free-solid-svg-icons";
import { faCouch } from "@fortawesome/free-solid-svg-icons";
import { faEnvelope } from "@fortawesome/free-solid-svg-icons";
import { faSortDown } from "@fortawesome/free-solid-svg-icons";
import { faSortUp } from "@fortawesome/free-solid-svg-icons";
import { faComment } from "@fortawesome/free-solid-svg-icons";
import { faVenusMars } from "@fortawesome/free-solid-svg-icons";
import { faWindowClose } from "@fortawesome/free-solid-svg-icons";
import { faQuoteLeft } from "@fortawesome/free-solid-svg-icons";
import { faBriefcase } from "@fortawesome/free-solid-svg-icons";
import { faBook } from "@fortawesome/free-solid-svg-icons";
import { faMapMarkerAlt } from "@fortawesome/free-solid-svg-icons";
import { faLock } from "@fortawesome/free-solid-svg-icons";
import { faUser } from "@fortawesome/free-solid-svg-icons";
import { faSearch } from "@fortawesome/free-solid-svg-icons";
import { faFacebook } from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

// library.add(faCoffee);
library.add(faCoffee, faJs, faVuejs);
library.add(faCouch);
library.add(faEnvelope);
library.add(faSortDown);
library.add(faSortUp);
library.add(faComment);
library.add(faVenusMars);
library.add(faWindowClose);
library.add(faQuoteLeft);
library.add(faBriefcase);
library.add(faBook);
library.add(faMapMarkerAlt);
library.add(faLock);
library.add(faUser);
library.add(faSearch);
library.add(faFacebook);

Vue.component("font-awesome-icon", FontAwesomeIcon);